### ISSUE TITLE
Can this be published to NPM?

### ISSUE THREAD

**Issue by ghost** [cschoi3/US-states-and-cities-json#2]
Hello - can this package be published to NPM so we just need to import the module?

**Comment by cschoi3** [comment]
Sure thing, I’ll work on getting it up

**Comment by ghost** [comment]
Thanks! I'll wait for that one. Very timely lol - working on a project that needs autofilling of US states and cities. Thanks again

**Comment by ghost** [comment]
And maybe, for further improvements, we could reformat the JSON as 

```
{
  state: "StateX",
  abbreviation: "cx",
  cities: [...cities]
}
```

**Comment by cschoi3** [comment]
^ question, have you thought on how would you be associating a particular state with its cities in the format you've outlined above?  and actually after giving some thought to it, rather than publishing this file to npm, you could just download and inject into your database or even include it as a data file in your project, no?

**Comment by ghost** [comment]
Actually, I downloaded and minified the data.json file and added it in project. I was just thinking if publishing this one to npm will have an effect to the app's bundle size (though may not be that much).
Also, it would be easier to import. 

My project covers US states/cities and Canada provinces/municipalities. Kindly check [https://github.com/jprichardson/node-canada](url) if you like - I'm using this one for simple Canada lookups. Cheers

**Comment by cschoi3** [comment]
^ can't seem to open the node-canada repo and cool, minifying the data and adding it to your project is the way i would go about this as well

**Comment by ghost** [comment]
Can I fork this one and create a NPM version and attribute you?

**Comment by cschoi3** [comment]
For sure, go right ahead
